name: 'Is mergeable'
description: 'Check if current pull request is mergeable'
author: 'Celine Kurpershoek'
branding: 
  icon: 'message-circle'
  color: 'green'
inputs: 
  repo:
    description: 'Github repository name (automatically created by Github)'
    required: true
  pullNumber:
    description: 'Github pullrequest number (automatically created by Github)'
    required: true
outputs:
  result: # id of output
    description: 'Is this PR mergeable > boolean'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.pullNumber }}
