name: Check if mergable
on:
  pull_request

jobs: 
  job:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Run check
        uses: './'
        with:  
          repo: ${{ github.repository }}
          pullNumber: ${{ github.event.pull_request.number }}
        
