name: Check if mergable
on:
  push

jobs: 
  job:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - run:   echo echo ::set-output name=result::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        id: getPullNumber
        shell: bash
      - name: Run check
        uses: celinekurpershoek/is-mergable@master
        with:  
          repo: ${{ github.repository }}
          pullNumber: ${{ steps.getPullNumber.outputs.result }}
