name: Check if mergable
on:
  pull_request

jobs: 
  job:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: echo "The PR number is $PR_NUMBER"
      - name: Run check
        uses: celinekurpershoek/is-mergable@master
        with:  
          repo: ${{ github.repository }}
          pullNumber: ${{ github.event.pull_request.number }}
        
